#!/usr/bin/env python3
"""Build the Veracode API tube-style map.

Generated by batch generator. 
"""

import sys
from pathlib import Path

sys.path.insert(0, "/Users/kinlane/GitHub/all/.claude/skills")
from _subway_engine import build_subway  # noqa: E402

ABBREV = {

}

LINES = [
    {
        "name": 'Veracode AppSec',
        "color": '#0060A1',
        "closed": True,
        "stations": [
        ('Applications', (640, 260)),
        ('Findings', (840, 460)),
        ('Identity', (640, 660)),
        ('Reporting', (440, 460)),
        ],
    },
]

URL_OVERRIDES = {
    'Applications': 'https://apis.apis.io/apis/veracode/veracode-applications-api/',
    'Findings': 'https://apis.apis.io/apis/veracode/veracode-findings-api/',
    'Identity': 'https://apis.apis.io/apis/veracode/veracode-identity-api/',
    'Reporting': 'https://apis.apis.io/apis/veracode/veracode-reporting-api/',
}


def main():
    seen = set()
    n_unique = 0
    for ln in LINES:
        for (st, _) in ln["stations"]:
            if st not in seen:
                n_unique += 1
                seen.add(st)
    build_subway(
        title='The Veracode API · Underground Map',
        subtitle=f"{n_unique} APIs · {len(LINES)} functional lines · click any station for the apis.io page",
        lines=LINES,
        abbrev=ABBREV,
        source_label='Source: veracode/openapi · github.com/api-evangelist/veracode',
        out_dir=Path(__file__).resolve().parent,
        out_basename='veracode-subway-map',
        provider_id='veracode',
        station_url_overrides=URL_OVERRIDES,
    )


if __name__ == "__main__":
    main()
